# permissions for end users to view upcxxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upcxx-viewer-role
rules:
- apiGroups:
  - pgas.github.com
  resources:
  - upcxxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pgas.github.com
  resources:
  - upcxxes/status
  verbs:
  - get
